name: Auto Sync Vless Worker JS

on:
  schedule:
    - cron: "0 1 * * *"  # æ¯å¤©å‡Œæ™¨ 1 ç‚¹æ‰§è¡Œ
  workflow_dispatch:      # æ”¯æŒæ‰‹åŠ¨æ‰§è¡Œ

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: åˆå§‹åŒ–ä»“åº“
        uses: actions/checkout@v4

      - name: ä¸‹è½½æœ€æ–° JS æ–‡ä»¶
        run: |
          echo -e "\033[34m[ä¸‹è½½æœ€æ–° vless.js]\033[0m"
          curl -L -o "vlessæ— éœ€proxyipçš„nat64å¥—å£³ç‰ˆ (æ¨èä½¿ç”¨).js" "https://raw.githubusercontent.com/yonggekkk/Cloudflare-vless-trojan/refs/heads/main/Vless_workers_pages/vless%E6%97%A0%E9%9C%80proxyip%E7%9A%84nat64%E5%A5%97%E5%A3%B3%E7%89%88%20(%E6%8E%A8%E8%8D%90%E4%BD%BF%E7%94%A8).js"

      - name: è‡ªåŠ¨æäº¤
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ğŸ”„ è‡ªåŠ¨åŒæ­¥æœ€æ–° JS"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          push_options: --force
